a = str('Bohdan')
b = str('Vlasiuk')
date = int(12)
month = int(4)
year = int(2020)
print(a, b, sep=' ')
print('Home work')
print('Добрий день', a, b)
print(date, month, year, sep='/', end=' -')
print(' гарний день для вивчення Python')
